name: Release tagging
on:
 pull_request:
   branches:
     - main
   types:
     - closed
jobs:
 main:
   runs-on: ubuntu-latest
   if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
   steps:
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
      - name: Echo tag
        run: echo ${{ steps.tag.outputs.result }}
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ steps.tag.outputs.result }}
